### ISSUE TITLE
Possible "silence" window for the bot

### ISSUE THREAD

**Issue by Felanbird** [RAnders00/bot-titlechange#1]
![vEiwwQg](https://user-images.githubusercontent.com/41973452/62645646-a597fb80-b91a-11e9-8b61-0b8722c6609b.png)

**Comment by Felanbird** [comment]
**_bump_**

![image](https://user-images.githubusercontent.com/41973452/94756152-aed8f880-0364-11eb-84ff-1e0152cd4dc5.png)

\>(

**Comment by RAnders00** [comment]
you can now timeout the bot and the bot will properly shut up and not post the messages after the timeout expires so i think this can be closed?

**Comment by Felanbird** [comment]
I will test this one second

**Comment by Felanbird** [comment]
I have tested and this is indeed implemented via timeout.

**Comment by Felanbird** [comment]
@fawcan
